# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _acos_sounding_id.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_acos_sounding_id', [dirname(__file__)])
        except ImportError:
            import _acos_sounding_id
            return _acos_sounding_id
        if fp is not None:
            try:
                _mod = imp.load_module('_acos_sounding_id', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _acos_sounding_id = swig_import_helper()
    del swig_import_helper
else:
    import _acos_sounding_id
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x



_acos_sounding_id.SHARED_PTR_DISOWN_swigconstant(_acos_sounding_id)
SHARED_PTR_DISOWN = _acos_sounding_id.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.hdf_sounding_id
import full_physics_swig.generic_object
class AcosSoundingId(full_physics_swig.hdf_sounding_id.HdfSoundingId):
    """

    This class reads a given file, and extracts out the sounding
    information.

    This determine the index into the HDF file for the given sounding
    (referred to as "frame number"), and determines which sounding we
    are using (s or p), or if we are doing averaging.

    C++ includes: acos_sounding_id.h 
    """
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    S_SOUNDING = _acos_sounding_id.AcosSoundingId_S_SOUNDING
    P_SOUNDING = _acos_sounding_id.AcosSoundingId_P_SOUNDING
    __swig_destroy__ = _acos_sounding_id.delete_AcosSoundingId

    def __init__(self, File, Sounding_id, st):
        """

        AcosSoundingId::AcosSoundingId(const HdfFile &File, const std::string &Sounding_id, SoundingType
        Sounding_type)
        Read Hdf file and determine sounding id information.

        Parameters:
        -----------

        File:  The file to read.

        Sounding_id:  The sounding ID.

        Sounding_type:  Specify if we have S, P. 
        """
        _acos_sounding_id.AcosSoundingId_swiginit(self, _acos_sounding_id.new_AcosSoundingId(File, Sounding_id, st))

    def create(File, Sounding_id):
        """

        std::vector< boost::shared_ptr< HdfSoundingId > > AcosSoundingId::create(const HdfFile &File, const std::string &Sounding_id)
        Parse a sounding ID string.

        This string indicates if we are doing just a P retrieval, just a S
        retrieval, or averaging the two.

        The sounding ID should be in the format: 20090726171701S - use the S
        band

        20090726171701P - use the P band

        20090726171701 - Average the two bands

        This return a vector of AcosSoundingId, length 1 if we are not
        averaging or length 2 if we are averaging. 
        """
        return _acos_sounding_id.AcosSoundingId_create(File, Sounding_id)

    create = staticmethod(create)
AcosSoundingId_swigregister = _acos_sounding_id.AcosSoundingId_swigregister
AcosSoundingId_swigregister(AcosSoundingId)

def AcosSoundingId_create(File, Sounding_id):
    """

    std::vector< boost::shared_ptr< HdfSoundingId > > AcosSoundingId::create(const HdfFile &File, const std::string &Sounding_id)
    Parse a sounding ID string.

    This string indicates if we are doing just a P retrieval, just a S
    retrieval, or averaging the two.

    The sounding ID should be in the format: 20090726171701S - use the S
    band

    20090726171701P - use the P band

    20090726171701 - Average the two bands

    This return a vector of AcosSoundingId, length 1 if we are not
    averaging or length 2 if we are averaging. 
    """
    return _acos_sounding_id.AcosSoundingId_create(File, Sounding_id)



