# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _cost_function.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_cost_function')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_cost_function')
    _cost_function = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cost_function', [dirname(__file__)])
        except ImportError:
            import _cost_function
            return _cost_function
        try:
            _mod = imp.load_module('_cost_function', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _cost_function = swig_import_helper()
    del swig_import_helper
else:
    import _cost_function
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


SHARED_PTR_DISOWN = _cost_function.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.generic_object
class CostFunction(full_physics_swig.generic_object.GenericObject):
    """

    This class calculates a cost function, along with a jacobian.

    C++ includes: cost_function.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cost_function.delete_CostFunction

    def cost_function(self, X):
        """

        virtual void FullPhysics::CostFunction::cost_function(const blitz::Array< double, 1 > &X, blitz::Array< double, 1 >
        &Residual, blitz::Array< double, 1 > &Se, blitz::Array< double, 2 >
        &Jacobian) const =0
        For the given value of X, calculate the residuals and jacobians.

        The residual is defined as F(x) - y, so the Jacobian of the residuals
        is the same as the Jacobian of F(x).

        Parameters:
        -----------

        X:  Input value

        Residual:  On exit, set to the residual of the cost function

        Se:  On exit, the covariance of the residual. We assume the covariance
        is a diagonal matrix, and just return the diagonal elements

        Jacobian:  On exit, the Jacobian of the cost function. 
        """
        return _cost_function.CostFunction_cost_function(self, X)

CostFunction.__str__ = new_instancemethod(_cost_function.CostFunction___str__, None, CostFunction)
CostFunction.cost_function = new_instancemethod(_cost_function.CostFunction_cost_function, None, CostFunction)
CostFunction_swigregister = _cost_function.CostFunction_swigregister
CostFunction_swigregister(CostFunction)



