# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _ils_convolution.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ils_convolution')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ils_convolution')
    _ils_convolution = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ils_convolution', [dirname(__file__)])
        except ImportError:
            import _ils_convolution
            return _ils_convolution
        try:
            _mod = imp.load_module('_ils_convolution', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ils_convolution = swig_import_helper()
    del swig_import_helper
else:
    import _ils_convolution
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


SHARED_PTR_DISOWN = _ils_convolution.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.ils
import full_physics_swig.state_vector
import full_physics_swig.generic_object
import full_physics_swig.dispersion
class IlsConvolution(full_physics_swig.ils.Ils, full_physics_swig.dispersion.ObserverDispersion):
    """

    This is a ILS where we use a Dispersion object to determine the
    wavenumbers of each pixel, and convolve against a IlsFunction.

    C++ includes: ils_convolution.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """

        FullPhysics::IlsConvolution::IlsConvolution(const boost::shared_ptr< Dispersion > &Disp, const boost::shared_ptr<
        IlsFunction > &Ils_func, double Ils_half_width)
        Constructor. 
        """
        _ils_convolution.IlsConvolution_swiginit(self, _ils_convolution.new_IlsConvolution(*args))

    def notify_update(self, *args):
        """

        virtual void FullPhysics::IlsConvolution::notify_update(const Dispersion &D)

        """
        return _ils_convolution.IlsConvolution_notify_update(self, *args)


    def apply_ils(self, *args):
        """

        ArrayAd< double, 1 > IlsConvolution::apply_ils(const blitz::Array< double, 1 > &High_resolution_wave_number, const
        ArrayAd< double, 1 > &High_resolution_radiance, const std::vector< int
        > &Pixel_list) const

        """
        return _ils_convolution.IlsConvolution_apply_ils(self, *args)


    def _v_ils_function(self):
        """

        boost::shared_ptr<IlsFunction> FullPhysics::IlsConvolution::ils_function() const
        Underlying IlsFunction. 
        """
        return _ils_convolution.IlsConvolution__v_ils_function(self)


    @property
    def ils_function(self):
        return self._v_ils_function()


    def _v_dispersion(self):
        """

        boost::shared_ptr<Dispersion> FullPhysics::IlsConvolution::dispersion() const
        Underlying dispersion. 
        """
        return _ils_convolution.IlsConvolution__v_dispersion(self)


    @property
    def dispersion(self):
        return self._v_dispersion()

    __swig_destroy__ = _ils_convolution.delete_IlsConvolution
IlsConvolution.notify_update = new_instancemethod(_ils_convolution.IlsConvolution_notify_update, None, IlsConvolution)
IlsConvolution.apply_ils = new_instancemethod(_ils_convolution.IlsConvolution_apply_ils, None, IlsConvolution)
IlsConvolution._v_ils_function = new_instancemethod(_ils_convolution.IlsConvolution__v_ils_function, None, IlsConvolution)
IlsConvolution._v_dispersion = new_instancemethod(_ils_convolution.IlsConvolution__v_dispersion, None, IlsConvolution)
IlsConvolution_swigregister = _ils_convolution.IlsConvolution_swigregister
IlsConvolution_swigregister(IlsConvolution)



