# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _initial_guess_value.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_initial_guess_value')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_initial_guess_value')
    _initial_guess_value = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_initial_guess_value', [dirname(__file__)])
        except ImportError:
            import _initial_guess_value
            return _initial_guess_value
        try:
            _mod = imp.load_module('_initial_guess_value', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _initial_guess_value = swig_import_helper()
    del swig_import_helper
else:
    import _initial_guess_value
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


SHARED_PTR_DISOWN = _initial_guess_value.SHARED_PTR_DISOWN

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import full_physics_swig.composite_initial_guess
import full_physics_swig.generic_object
import full_physics_swig.initial_guess
class InitialGuessValue(full_physics_swig.composite_initial_guess.InitialGuessBuilder):
    """

    This is a simple implementation of InitialGuessBuilder that just has
    variables used to give the apriori, initial guess, and covariance.

    Since the initial guess of often just the apriori, the initial guess
    is allowed to be left empty and we just use the apriori in that case.

    C++ includes: initial_guess_value.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    __swig_destroy__ = _initial_guess_value.delete_InitialGuessValue

    @property
    def number_element(self):
        return self._v_number_element()


    def _v_apriori(self, *args):
        """

        void FullPhysics::InitialGuessValue::apriori(const blitz::Array< double, 1 > &v)
        Set apriori value. 
        """
        return _initial_guess_value.InitialGuessValue__v_apriori(self, *args)


    @property
    def apriori(self):
        return self._v_apriori()

    @apriori.setter
    def apriori(self, value):
      self._v_apriori(value)


    def _v_apriori_covariance(self, *args):
        """

        void FullPhysics::InitialGuessValue::apriori_covariance(const blitz::Array< double, 2 > &m)
        Set apriori covariance value. 
        """
        return _initial_guess_value.InitialGuessValue__v_apriori_covariance(self, *args)


    @property
    def apriori_covariance(self):
        return self._v_apriori_covariance()

    @apriori_covariance.setter
    def apriori_covariance(self, value):
      self._v_apriori_covariance(value)


    def apriori_subset(self, Flag, V):
        """

        void InitialGuessValue::apriori_subset(const blitz::Array< bool, 1 > &Flag, const blitz::Array< double, 1 >
        &V)
        Subset a value to include only those elements where Flag is true. 
        """
        return _initial_guess_value.InitialGuessValue_apriori_subset(self, Flag, V)


    def apriori_covariance_subset(self, Flag, V):
        """

        void InitialGuessValue::apriori_covariance_subset(const blitz::Array< bool, 1 > &Flag, const blitz::Array< double, 2 >
        &V)
        Subset a value to include only those elements where Flag is true. 
        """
        return _initial_guess_value.InitialGuessValue_apriori_covariance_subset(self, Flag, V)


    def _v_initial_guess(self, *args):
        """

        void FullPhysics::InitialGuessValue::initial_guess(const blitz::Array< double, 1 > &v)
        Set first guess value. 
        """
        return _initial_guess_value.InitialGuessValue__v_initial_guess(self, *args)


    @property
    def initial_guess(self):
        return self._v_initial_guess()

    @initial_guess.setter
    def initial_guess(self, value):
      self._v_initial_guess(value)


    def __init__(self):
        _initial_guess_value.InitialGuessValue_swiginit(self, _initial_guess_value.new_InitialGuessValue())
InitialGuessValue._v_apriori = new_instancemethod(_initial_guess_value.InitialGuessValue__v_apriori, None, InitialGuessValue)
InitialGuessValue._v_apriori_covariance = new_instancemethod(_initial_guess_value.InitialGuessValue__v_apriori_covariance, None, InitialGuessValue)
InitialGuessValue.apriori_subset = new_instancemethod(_initial_guess_value.InitialGuessValue_apriori_subset, None, InitialGuessValue)
InitialGuessValue.apriori_covariance_subset = new_instancemethod(_initial_guess_value.InitialGuessValue_apriori_covariance_subset, None, InitialGuessValue)
InitialGuessValue._v_initial_guess = new_instancemethod(_initial_guess_value.InitialGuessValue__v_initial_guess, None, InitialGuessValue)
InitialGuessValue_swigregister = _initial_guess_value.InitialGuessValue_swigregister
InitialGuessValue_swigregister(InitialGuessValue)



