#! /usr/bin/env ruby
# This compare two L2 HDF files, giving the right tolerance for each field.
require 'getoptlong'

rel_diff = 4.5e-3
apos_diff = 6e-2

report = ""
opts = GetoptLong.new(
["--report", "-r", GetoptLong::NO_ARGUMENT]
)
opts.each do |opt, arg|
  report = "-r" if(opt == "--report")
end
if(ARGV.size != 2)
  puts <<END
This compares two HDF L2 files. We look for all numbers to have a
relative difference of #{rel_diff}, except for
aposterori_covariance_matrix, averaging_kernel_matrix,
xco2_correlation_interf, and interference_smoothing_uncert which tend
to have larger differences. We compare those to an absolute difference of #{apos_diff}.

The "--report | -r" option prints out the differences (the default is to
just print the total number of differences).
END
  exit 1
end
dlist = []
`h5ls -r #{ARGV[0]}`.split("\n").each do |ln|
  t = ln.split
  dlist << t[0] if(t[1] =="Dataset")
end
ok = true
dlist.each do |dname|
  unless(dname == "/RetrievalResults/aposteriori_covariance_matrix" ||
         dname =="/RetrievalResults/aerosol_ice_profile_log_param_uncert" ||
         dname =="/RetrievalResults/aerosol_kahn_2b_profile_log_param_uncert" ||
         dname =="/RetrievalResults/aerosol_kahn_3b_profile_log_param_uncert" ||
         dname =="/RetrievalResults/aerosol_water_profile_log_param_uncert" ||
         dname == "/RetrievalResults/co2_profile_averaging_kernel_matrix" ||
         dname == "/RetrievalResults/averaging_kernel_matrix" ||
         dname == "/RetrievalResults/interference_smoothing_uncert" ||
         dname =~ /brdf_/ ||
         dname == "/RetrievalResults/xco2_correlation_interf" ||
         dname == "/RetrievalResults/xco2_gain_vector")
    if(dname == "/RetrievalResults/xco2_uncert_interf")
      system "h5diff #{report} -p 2e-2 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname == "/Forward_Model_Errors/Spectroscopy/temperature/o2/derivative")
      system "h5diff #{report} -p 1e-1 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =~ /aerosol_.*_aod_(low|mid|high)/ ||
          dname =~ /aerosol_.*_aod/ ||
          dname =~ /aerosol_aod/
          )
      system "h5diff #{report} -d 1e-2 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =~ /aerosol_.*_log_param/)
      system "h5diff #{report} -p 1e-2 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =~ /aerosol_param/)
      system "h5diff #{report} -d 0.1 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =~ /vector_altitude_levels/)
      system "h5diff #{report} -d 0.1 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =~ /zero_level_offset/)
      system "h5diff #{report} -p 1e-2 #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname == "/RetrievedStateVector/state_vector_result")
      # We can't easily compare state_vector_results because is mixes things with
      # wildly different scales so there is no natural tolerance to use. However
      # all the piece of state_vector_results get reported as other fields, so
      # we can just skip state_vector_results.
    elsif(dname == "/Forward_Model_Errors/Spectroscopy/temperature/o2/description")
      # Contains path information that changes depending on the system run on,
      # so skip comparison
    elsif(dname == "/RetrievalResults/co2_profile_covariance_matrix")
      # Skip, different between centos 6 and 7
    elsif(dname == "/SpectralParameters/modeled_radiance")
      system "h5diff #{report} -p 5e-3  #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname == "/RetrievalResults/dof_co2_profile")
      system "h5diff #{report} -p 1e-3  #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname == "/RetrievalResults/temperature_offset_fph")
      system "h5diff #{report} -d 5e-2  #{ARGV[0]} #{ARGV[1]} #{dname}"
    elsif(dname =="/RetrievalResults/albedo_slope_uncert_o2" ||
  	  dname =="/RetrievalResults/albedo_uncert_o2_fph" ||
	  dname =="/RetrievalResults/albedo_slope_uncert_strong_co2" ||
	  dname =="/RetrievalResults/albedo_slope_uncert_weak_co2" ||
  	  dname =="/RetrievalResults/albedo_uncert_strong_co2_fph" ||
  	  dname =="/RetrievalResults/albedo_uncert_weak_co2_fph" ||
  	  dname =="/RetrievalResults/albedo_slope_weak_co2" ||
  	  dname =="/RetrievalResults/albedo_slope_strong_co2" ||
  	  dname =="/RetrievalResults/albedo_slope_o2" ||
  	  dname =="/RetrievalResults/albedo_o2_fph" ||
	  dname =="/RetrievalResults/xco2_uncert" ||
	  dname =="/RetrievalResults/xco2_uncert_noise" ||
	  dname =="/RetrievalResults/xco2_uncert_smooth" ||
	  dname =="/RetrievedStateVector/state_vector_aposteriori_uncert" ||
	  dname =="/RetrievalResults/temperature_offset_uncert_fph" ||
          dname =="/RetrievalResults/surface_pressure_uncert_fph" ||
          dname =="/RetrievalResults/h2o_scale_factor_uncert" ||
	  dname =="/RetrievalResults/dof_full_vector" ||
	  dname =="/RetrievalResults/eof_3_scale_o2" ||
	  dname =="/RetrievalResults/xco2_avg_kernel" ||
          dname =="/RetrievalResults/co2_profile_uncert" ||
          dname =="/RetrievalResults/xco2_gain_vector" ||
	  dname =="/RetrievalResults/xco2_avg_kernel_norm" ||
  	  dname =="/RetrievalResults/fluorescence_at_reference" ||
          dname =="/RetrievalResults/fluorescence_at_reference_uncert")
      system "h5diff #{report} -p 6e-2  #{ARGV[0]} #{ARGV[1]} #{dname}"
    else
      system "h5diff #{report} -p #{rel_diff} #{ARGV[0]} #{ARGV[1]} #{dname}"
    end
  else
    # This tends to vary *alot*. I'm not sure that there isn't something
    # wrong with this calculation, but for now don't trigger an error if we
    # are vaguely close to the expected results
    if(dname == "/RetrievalResults/averaging_kernel_matrix" ||
       dname == "/RetrievalResults/aposteriori_covariance_matrix" ||
       dname == "/RetrievalResults/xco2_gain_vector"
       )
      # Skip all checks
    else
      system "h5diff #{report} -d #{apos_diff} #{ARGV[0]} #{ARGV[1]} #{dname}"
    end
  end
  ok = false if($? != 0)
end
exit 1 unless(ok)


